# Generated by Django 4.0.3 on 2022-04-26 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("wagtailcore", "0071_populate_revision_content_type"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="revision",
            name="content_object_idx",
        ),
        migrations.RemoveIndex(
            model_name="revision",
            name="base_content_object_idx",
        ),
        migrations.AlterField(
            model_name="revision",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                related_name="+",
            ),
        ),
        migrations.AlterField(
            model_name="revision",
            name="base_content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                related_name="+",
            ),
        ),
        migrations.AddIndex(
            model_name="revision",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="content_object_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="revision",
            index=models.Index(
                fields=["base_content_type", "object_id"],
                name="base_content_object_idx",
            ),
        ),
    ]
