# Generated by Django 4.2.dev20221212151407 on 2022-12-12 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("wagtailcore", "0081_populate_workflowstate_content_type"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="workflowstate",
            name="unique_in_progress_workflow",
        ),
        migrations.RemoveIndex(
            model_name="WorkflowState",
            name="workflowstate_ct_id_idx",
        ),
        migrations.RemoveIndex(
            model_name="WorkflowState",
            name="workflowstate_base_ct_id_idx",
        ),
        migrations.AlterField(
            model_name="workflowstate",
            name="base_content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="workflowstate",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowstate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ("in_progress", "needs_changes"))),
                fields=("base_content_type", "object_id"),
                name="unique_in_progress_workflow",
            ),
        ),
        migrations.AddIndex(
            model_name="WorkflowState",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="workflowstate_ct_id_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="WorkflowState",
            index=models.Index(
                fields=["base_content_type", "object_id"],
                name="workflowstate_base_ct_id_idx",
            ),
        ),
    ]
